export const TRAIN_NUMBER_INPUT_CHANGED = 'TRAIN_NUMBER_INPUT_CHANGED';
export const SEARCH_TRAIN_NUMBER = 'SEARCH_TRAIN_NUMBER';
export const FETCH_TRAIN_DATA_SUCCESS = 'FETCH_TRAIN_DATA_SUCCESS';
export const FETCH_STATION_QUESTIONS = 'FETCH_STATION_QUESTIONS';
export const FETCH_STATION_QUESTIONS_SUCCESS = 'FETCH_STATION_QUESTIONS_SUCCESS';
